version: "3.9"

services:

  api:

    build: .

    container_name: churn-api

    ports:
      - "8000:8000"

    restart: unless-stopped

    volumes:
      - ./artifacts:/app/artifacts

    depends_on:
      - mlflow



  mlflow:

    image: python:3.11-slim

    container_name: mlflow-server

    working_dir: /app

    volumes:
      - .:/app

    command: >
      bash -c "
      pip install mlflow &&
      mlflow ui
      --host 0.0.0.0
      --port 5000
      "

    ports:
      - "5000:5000"

    restart: unless-stopped